//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Comment
{
	public virtual User To
	{
		get;
		set;
	}

	public virtual User From
	{
		get;
		set;
	}

}

