//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Guardian : User
{
	public virtual IEnumerable<GuardianOffer> GuardianOffers
	{
		get;
		set;
	}

	public virtual IEnumerable<OwnerOffer> AcceptedOffers
	{
		get;
		set;
	}

}

