//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual Address Address
	{
		get;
		set;
	}

	public virtual IEnumerable<Message> Message
	{
		get;
		set;
	}

	public virtual IEnumerable<Comment> Comments
	{
		get;
		set;
	}

	public virtual void Login(object string userName, object string password)
	{
		throw new System.NotImplementedException();
	}

}

